config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'about' => 'homes#about'

  resources :users, only: %i[edit update] do
    collection do
      get 'my_page'
      get 'quit'
      patch 'out'
    end
  end

  resources :events, only: %i[index new create show edit update destroy] do
    resources :maps, only: %i[create edit update destroy]
    resources :images, only: %i[create destroy]
  end
  get 'event/day' => 'events#day'
  get 'event/tag' => 'events#tag'

  resources :presets, only: %i[new create destroy]

  resources :groups, only: %i[index create show edit update] do
    get 'day'
  end

  resources :group_users, only: %i[create destroy]
  patch 'group_users/:id' => 'group_users#accept', as: :group_users_accept
  get 'group_users/:id' => 'group_users#reject', as: :group_users_reject
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.has_translation(*attributes)
    attributes.each do |attribute|
      define_method "#{attribute}" do
        self.send "#{attribute}_#{I18n.locale}"
      end
    end
  end

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :maps
  has_many :images, dependent: :destroy
  has_many  :tag_relationships, dependent: :destroy
  has_many  :tags, through: :tag_relationships
  accepts_attachments_for :images, attachment: :image, append: true

  # バリデーション
  validates :name, presence: true, length: { maximum: 20 }
  validates :place, length: { maximum: 20 }
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :end_time_check
  # 終了が開始より早くならないこと
  def end_time_check
    errors.add(:end_time, 'は開始時刻より遅い時間を選択してください') if start_time.present? && end_time.present? && (end_time < start_time)
  end

  # タグ機能
  def save_tags(save_event_tags)
    current_tags = tags.pluck(:name) unless tags.nil?  # タグがあればnameを抽出
    old_tags = current_tags - save_event_tags
    new_tags = save_event_tags - current_tags

    old_tags.each do |old_name|
      tags.delete Tag.find_by(name: old_name)
    end

    new_tags.each do |new_name|
      event_tag = Tag.find_or_create_by(name: new_name)
      tags << event_tag
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true, length: { maximum: 20 }
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :group_id, presence: true, uniqueness: { scope: [:user_id] }
  # validates :user_id, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :event

  attachment :image
end

app/models/map.rb
class Map < ApplicationRecord
  belongs_to :event

  validates :latitude, :longitude, :address, presence: true
  validates :name, presence: true, length: { maximum: 10 }

  geocoded_by :address
  before_validation :geocode
end

app/models/preset.rb
class Preset < ApplicationRecord

  belongs_to :user

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_relationships, dependent: :destroy
  has_many :events, through: :tag_relationships
  validates :name, presence: true, length: { maximum: 10 }
end

app/models/tag_relationship.rb
class TagRelationship < ApplicationRecord
  belongs_to :event
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :events, dependent: :destroy
  has_many :presets, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users

  validates :name, presence: true, length: { minimum: 2, maximum: 15 }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    # ログイン中のユーザーが所属するグループのみ抽出
    group_ids = current_user.group_users.pluck(:group_id)
    @groups = Group.where(id: group_ids).order(updated_at: :desc)
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      group_user = @group.group_users.new(user: current_user, invitation: true) # 作成したユーザーは招待済みにする
      group_user.save
      group_ids = current_user.group_users.pluck(:group_id)
      @groups = Group.where(id: group_ids).order(updated_at: :desc)
    else
      group_ids = current_user.group_users.pluck(:group_id)
      @groups = Group.where(id: group_ids).order(updated_at: :desc)
      render 'index'
    end
  end

  def show
    @group = Group.find_by_id(params[:id])
    if @group == nil  #存在しないIDなら一覧画面に飛ばす
      redirect_to groups_path
      return
    end
    true_group_users = @group.group_users.where(invitation: true)
    true_user_ids = true_group_users.pluck(:user_id)
    false_group_users = @group.group_users.where(invitation: false)
    false_user_ids = false_group_users.pluck(:user_id)
    if true_user_ids.include?(current_user.id)  #アクセス制限
      @users = User.where(id: true_user_ids)
      @events = Event.where(user_id: @users.ids, release: true)
      invitation_group_users = @group.group_users.where(invitation: false)
      invitation_user_ids = invitation_group_users.pluck(:user_id)
      @invitation_users = User.where(id: invitation_user_ids)
    elsif false_user_ids.include?(current_user.id)
      flash[:faile] = '招待を承認してください'
      redirect_to groups_path
    else
      flash[:faile] = 'グループに所属していません'
      redirect_to groups_path
    end
  end

  def edit
    @group = Group.find_by_id(params[:id])
    if @group == nil  #存在しないIDなら一覧画面に飛ばす
      redirect_to groups_path
      return
    end
    group_users = @group.group_users.where(invitation: true)
    user_ids = group_users.pluck(:user_id)
    if user_ids.include?(current_user.id)  #アクセス制限
      @new_group_user = GroupUser.new
    else
      flash[:faile] = 'グループに所属していません'
      redirect_to groups_path
    end
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_path(@group)
    else
      group = Group.find(params[:id])
      @group.name = group.name
      @new_group_user = GroupUser.new
      render 'edit'
    end
  end

  def delete_user
    @group = Group.find(params[:id])
    @group.update(group_params)
    redirect_to group_path(@group)
  end

  def day
    group = Group.find(params[:group_id])
    users = group.users
    events = Event.where(user_id: users.ids, release: true)
    # カレンダーからクリックされた日付を取得
    @day = Time.zone.parse(params[:day].to_s)
    # クリックされた日付の０時以降に終わるもの（まだ終わってないもの）であり、
    # ２４時以前に始まるもの（明日の０時より前に始まるもの）
    @events = events.where('end_time>=? and start_time<?', @day, @day.tomorrow).order(:start_time)
    # 前日から続いてるものと今日はじまるものを分ける
    @before_events = @events.where('start_time<?', @day).order(:start_time)
    @today_events = @events.where('start_time>=?', @day).order(:start_time)
  end

  private

  def group_params
    params.require(:group).permit(:name)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top; end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def create
    event = Event.find(params[:event_id])
    map = event.maps.new(map_params)
    map.event_id = event.id
    if map.save
      flash[:success] = 'ピンが登録されました'
    else
      flash[:danger] = 'ピンが登録できませんでした'
    end
    redirect_to event_path(event)
  end

  def destroy
    map = Map.find(params[:event_id])
    event = map.event
    map.destroy
    redirect_to event_path(event)
  end

  def map_params
    params.require(:map).permit(:name, :address, :latitude, :longitude)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/presets_helper.rb
module PresetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_group_index.html.erb
<% if @groups.present? %>
<table class="table text-nowrap table-responsive">
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td class="group-index--group_name">
          <%= link_to group_path(group) do %>
            <%= group.name %>
          <% end %>
        </td>
        <% group.group_users.each do |group_user| %>
          <td class="group-index--user_name">
            <%= attachment_image_tag group_user.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
            <%= group_user.user.name %>
            <% if group_user.invitation == false %>
              <span class="group-index--user_name__invitation">
                招待中
              </span><br>
              <% if group_user.user_id == current_user.id %>
                <%= form_with(model: group_user, url:group_users_accept_path(id: group_user.id) ,class: "group-index--user_name__accept" ,local: true) do |f| %>
                  <%= f.hidden_field :invitation, :value => true %>
                  <%= f.submit "承認", class: "btn btn-sm btn-outline-success" %>
                <% end %>
                <%= link_to "拒否", group_users_reject_path(id: group_user.id), class: "btn btn-sm btn-outline-dark"  %>
              <% end %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>・グループに所属していません</p>
<% end %>

app/views/groups/_group_new_form.html.erb
<%= form_with model: @group do |f| %>
  <div>
    <%= f.text_field :name, placeholder: "グループ名", class: 'group-index--new-form' %>
    <%= f.submit '作成', class: 'btn btn-sm btn-outline-success opinion_field' %>
  </div>
<% end %>

app/views/groups/create.js.erb
$("#groups_area").html("<%= escape_javascript(render partial: 'groups/group_index', locals: {groups: @groups}) %>");
$("#group_name").val("");

app/views/groups/day.html.erb
<main class="group-day--main">
  <h3><%= @day.strftime('%m/%d') %>の予定</h3>
  <% if @events.present? %>
    <div class="table-responsive-md">
      <table class="table group-day--table">
        <% if @today_events.present? %>
          <thead class="thead-light">
            <tr scope="row">
              <th>
                <%= @day.strftime('%m/%d') %>から始まる予定
              </th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @today_events.each do |event| %>
              <tr scope="row">
                <td class="text-nowrap"><%= event.start_time.strftime('%m/%d %H:%M') %>　〜　<%= event.end_time.strftime('%m/%d %H:%M') %></td>
                <td class="text-nowrap">
                  <%= link_to event_path(event) do %>
                    <%= event.name %>
                  <% end %>
                </td>
                <td class="text-nowrap">
                  <% if event.place.present? %>
                    場所：<%= event.place %>
                  <% else %>
                    場所：-
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        <% end %>

        <% if @before_events.present? %>
          <thead class="thead-light">
            <tr scope="row">
              <th>
                前日から続いている予定
              </th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @before_events.each do |event| %>
              <tr scope="row">
                <td class="text-nowrap"><%= event.start_time.strftime('%m/%d %H:%M') %>　〜　<%= event.end_time.strftime('%m/%d %H:%M') %></td>
                <td class="text-nowrap">
                  <%= link_to event_path(event) do %>
                    <%= event.name %>
                  <% end %>
                </td>
                <td class="text-nowrap">
                  <% if event.place.present? %>
                    場所：<%= event.place %>
                  <% else %>
                    場所：-
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        <% end %>
      </table>
    </div>
  <% else %>
    <h5 class="text-center">登録された予定はありません</h5>
  <% end %>
</main>

app/views/groups/edit.html.erb
<div class="row">
  <div class="col-2"></div>
  <div class="col">
    <h4 class="group-edit--title"><%= @group.name %></h4>
  </div>
</div>
<div class="row group-edit--name-form">
  <div class="col-2"></div>
  <div class="col">
    <%= form_with(model: @group, local: true) do |f| %>
      <div>
        <%= f.label :"グループ名", class:"group-edit--name-form__label" %>
        <%= f.text_field :name, :size => "40*20", class:"group-edit--name-form__field" %>
        <%= f.submit "グループ名変更", class:"group-edit--name-form__btn" %>
      </div>
    <% end %>
    <%= render "layouts/error_messages", model: @group, attribute: :name %>
  </div>
</div>
<div class="row group-edit--table">
  <div class="col-2"></div>
  <div class="col-8 table-responsive-md">
    <table class="table">
      <thead class="thead-light">
        <tr scope="row">
          <th>グループメンバー</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @group.users.each do |user| %>
          <tr scope="row">
            <td class="text-nowrap">ユーザー名：<%= user.name %></td>
            <td class="text-nowrap">ユーザーID：<%= user.id %></td>
            <td class="text-nowrap">
              <%= link_to 'メンバーから外す', group_user_path(group_user: {user_id: user.id}, id: @group.id), method: :delete, class: "btn btn-outline-danger" %>
            </td>
          </tr>
        <% end %>
          <tr scope="row">
            <td  class="text-nowrap" colspan="3">

              <%= form_with(model: [@group, @new_group_user], url: group_users_path, local: true) do |form| %>
                <%= form.label :"ユーザーを追加", class:"group-edit--invitation-form" %>
                <%= form.text_field :user_id, class:"group-edit--invitation-form", :size => "40*20", placeholder: "ユーザーIDを入力してください"  %>
                <%= form.hidden_field :group_id, value: @group.id %>
                <%= form.submit "招待を送る" %>
              <% end %>
              <p class="group-edit--flash"><%= flash[:member] %></p>
            </td>
          </tr>
      </tbody>
    </table>
  </div>
  <div class="col-2"></div>
</div>

app/views/groups/index.html.erb
<% if flash[:success].present? %>
  <p class="alert alert-success" role="alert"><%= flash[:success] %></p>
<% end %>
<% if flash[:faile].present? %>
  <p class="alert alert-danger" role="alert"><%= flash[:faile] %></p>
<% end %>


<main class="group-index--main">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col">
      <h4 class="group-index--title">所属グループ一覧</h4>
    </div>
  </div>

  <div class="row">
    <div class="col-md-1">
    </div>
    <div class="col-md-10">
      <div id="groups_area">
        <%= render "groups/group_index" %>
      </div>
      
      <!--新規フォーム部分-->
      <div>
        <h5>グループを作成する</h5>
        <%= render "groups/group_new_form" %>
        <%= render "layouts/error_messages", model: @group, attribute: :name %>
      </div>
    </div>
  </div>
</main>

app/views/groups/show.html.erb
<% if flash[:success].present? %>
  <p class="alert alert-success" role="alert"><%= flash[:success] %></p>
<% end %>

<main class="group-show--main">
  <div class="row">
    <div class="col-2"></div>
    <div class="col-lg-9 d-flex align-items-end">
      <h4 class="group-show--title"><%= @group.name %></h4>
      <%= link_to '', edit_group_path(@group.id), class: 'fas fa-cog btn btn-outline-dark group-show--edit_btn' %>
    </div>
  </div>

  <div class="row">
    <!--sideBar-->
    <div class="col-lg-2 group-show--side">
      <!--予定追加部分-->
      <div class="group-show--event_new_btn">
        <%= link_to new_event_path, class: "group-show--new_link btn btn-sm btn-outline-success" do %>
          <span class="group-show--new_link_text">予定を追加　</span><i class="fas fa-plus-circle group-show--new_link_text"></i>
        <% end %>
      </div>
      <!--メンバー部分-->
      <h5 class="group-show--member-title"><i class="fas fa-user"></i> メンバー  <i class="fas fa-chevron-circle-right group-member-icon"></i></h5>
      <div class="group-show--member-box">
        <% @users.each do |user| %>
          <div class="group-show--member-box__member d-lg-flex align-items-center">
            <div class="mx-auto">
              <%= attachment_image_tag user, :profile_image, :fill, 80, 80, format: 'jpeg', fallback: "no_image.jpg", size:'80x80' %>
            </div>
          </div>
          <p class="text-lg-center group-show--member-box__name"><%= user.name %></p>
        <% end %>
        <!--招待中メンバー部分-->
        <h5 class="group-show--invitation-title text-center">招待中  <i class="fas fa-chevron-circle-right group-invitation-icon"></i></h5>
        <div class="group-show--invitation-title__box">
          <% if @invitation_users.present? %>
            <% @invitation_users.each do |user| %>
              <div class="group-show--invitation-title__box__img">
                <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
                <%= link_to '', group_user_path(group_user: {user_id: user.id}), method: :delete, class: "fas fa-user-minus btn btn-outline-dark group-show--invitation-title__box__delete-btn" %>
              </div>
              <p class="group-show--invitation-title__box__name text-left"><%= user.name %></p>
            <% end %>
          <% else %>
            <p class="text-center">招待中ユーザーはいません</p>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-lg-9 group-show--calendar">
      <!--カレンダー部分-->
      <div class="group-show--calendar-box">
        <%= week_calendar(number_of_weeks: 2, events: @events) do |date, events| %>
          <%= date.day %>
          <% events.first(10).each do |event| %>
            <div class="group-show--event">
              <%= link_to event_path(event), class: "group-show--event__link" do %>
                <p class="group-show--event__link__name"><%= event.name %></p>
              <% end %>
            </div>
          <% end %>

          <% if events.count >= 11 %>
            <div class="text-left event-index--day_dot">
              <i class="fas fa-ellipsis-v fa-xs"></i>
            </div>
          <% end %>

          <% if events.present? %>
            <div class="group-show--day-count">
              <%= link_to group_day_path(day: date, group_id: @group.id) do %>
                予定：<%= events.count %>件
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

</main>