config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'about' => 'homes#about'

  resources :users, only: %i[edit update] do
    collection do
      get 'my_page'
      get 'quit'
      patch 'out'
    end
  end

  resources :events, only: %i[index new create show edit update destroy] do
    resources :maps, only: %i[create edit update destroy]
    resources :images, only: %i[create destroy]
  end
  get 'event/day' => 'events#day'
  get 'event/tag' => 'events#tag'

  resources :presets, only: %i[new create destroy]

  resources :groups, only: %i[index create show edit update] do
    get 'day'
  end

  resources :group_users, only: %i[create destroy]
  patch 'group_users/:id' => 'group_users#accept', as: :group_users_accept
  get 'group_users/:id' => 'group_users#reject', as: :group_users_reject
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.has_translation(*attributes)
    attributes.each do |attribute|
      define_method "#{attribute}" do
        self.send "#{attribute}_#{I18n.locale}"
      end
    end
  end

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :maps
  has_many :images, dependent: :destroy
  has_many  :tag_relationships, dependent: :destroy
  has_many  :tags, through: :tag_relationships
  accepts_attachments_for :images, attachment: :image, append: true

  # バリデーション
  validates :name, presence: true, length: { maximum: 20 }
  validates :place, length: { maximum: 20 }
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :end_time_check
  # 終了が開始より早くならないこと
  def end_time_check
    errors.add(:end_time, 'は開始時刻より遅い時間を選択してください') if start_time.present? && end_time.present? && (end_time < start_time)
  end

  # タグ機能
  def save_tags(save_event_tags)
    current_tags = tags.pluck(:name) unless tags.nil?  # タグがあればnameを抽出
    old_tags = current_tags - save_event_tags
    new_tags = save_event_tags - current_tags

    old_tags.each do |old_name|
      tags.delete Tag.find_by(name: old_name)
    end

    new_tags.each do |new_name|
      event_tag = Tag.find_or_create_by(name: new_name)
      tags << event_tag
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true, length: { maximum: 20 }
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :group_id, presence: true, uniqueness: { scope: [:user_id] }
  # validates :user_id, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :event

  attachment :image
end

app/models/map.rb
class Map < ApplicationRecord
  belongs_to :event

  validates :latitude, :longitude, :address, presence: true
  validates :name, presence: true, length: { maximum: 10 }

  geocoded_by :address
  before_validation :geocode
end

app/models/preset.rb
class Preset < ApplicationRecord

  belongs_to :user

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_relationships, dependent: :destroy
  has_many :events, through: :tag_relationships
  validates :name, presence: true, length: { maximum: 10 }
end

app/models/tag_relationship.rb
class TagRelationship < ApplicationRecord
  belongs_to :event
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :events, dependent: :destroy
  has_many :presets, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users

  validates :name, presence: true, length: { minimum: 2, maximum: 15 }
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top; end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def create
    event = Event.find(params[:event_id])
    map = event.maps.new(map_params)
    map.event_id = event.id
    if map.save
      flash[:success] = 'ピンが登録されました'
    else
      flash[:danger] = 'ピンが登録できませんでした'
    end
    redirect_to event_path(event)
  end

  def destroy
    map = Map.find(params[:event_id])
    event = map.event
    map.destroy
    redirect_to event_path(event)
  end

  def map_params
    params.require(:map).permit(:name, :address, :latitude, :longitude)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_page
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to my_page_users_path
    else
      render :edit
    end
  end

  def quit; end

  def out
    user = current_user
    user.destroy
    redirect_to root_path
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/presets_helper.rb
module PresetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_with model:@user, local:true do |f| %>
<div class="row user-myPage--row">
  <div class="col-2"></div>
  <div class="col">
    <h5>ユーザーネーム：<%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class: "form-control name" %></h5>
  </div>
  <div class="col-2"></div>
</div>

<div class="row user-myPage--row">
  <div class="col-2"></div>
  <div class="col">
    <h5>メールアドレス：<%= f.text_field :email, autofocus: true, id:"inputName", class: "form-control introduction" %></h5>
  </div>
  <div class="col-2"></div>
</div>

<div class="row user-myPage--row">
  <div class="col-2"></div>
  <div class="col">
    <h5>ユーザー画像：<%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "" %></h5>
  </div>
  <div class="col-2"></div>
</div>

<div class="row user-myPage--row">
  <div class="col-2"></div>
  <div class="col">
    <h5><%= f.submit "情報を更新", class: "btn btn-outline-success" %></h5>
  </div>
  <div class="col-2"></div>
</div>
<% end %>

<div class="row user-myPage--row">
  <div class="col-2"></div>
  <div class="col">
    <p><%= link_to "退会する", quit_users_path, class: "btn btn-outline-danger quit-link" %></p>
  </div>
  <div class="col-2"></div>
</div>

app/views/users/my_page.html.erb
<div class="row user-myPage--row">
  <div class="col-2"></div>
  <div class="col">
    <h5>ユーザーネーム：<%= @user.name %></h5>
  </div>
  <div class="col-2"></div>
</div>

<div class="row user-myPage--row">
  <div class="col-2"></div>
  <div class="col">
    <h5>メールアドレス：<%= @user.email %></h5>
  </div>
  <div class="col-2"></div>
</div>

<div class="row user-myPage--row">
  <div class="col-2"></div>
  <div class="col">
    <h5>ユーザー画像：<%= attachment_image_tag @user, :profile_image, :fill, 160, 160, format: 'jpeg', fallback: "no_image.jpg", size:'160x160' %></h5>
  </div>
  <div class="col-2"></div>
</div>

<div class="row user-myPage--row">
  <div class="col-2"></div>
  <div class="col">
    <h5><%= link_to '編集する', edit_user_path(@user.id), class: 'btn btn-outline-secondary fas fa-user-cog' %></h5>
  </div>
  <div class="col-2"></div>
</div>

app/views/users/quit.html.erb
<div class="row user-myPage--row">
  <div class="col-2"></div>
  <div class="col">
    <h5 class="text-center">退会フォーム</h5>
  </div>
  <div class="col-2"></div>
</div>

<div class="row user-myPage--row">
  <div class="col-2"></div>
  <div class="col">
    <h5 class="text-center"><p><strong>本当に退会しますか？</strong></p></h5>
  </div>
  <div class="col-2"></div>
</div>

<div class="row user-myPage--row">
  <div class="col-2"></div>
  <div class="col">
    <p class="text-center">
      退会すると、会員情報や<br />
      登録した予定などが閲覧できなくなります。<br />
      退会する場合は、「退会する」をクリックしてください。
    </p>
  </div>
  <div class="col-2"></div>
</div>

<div class="row user-myPage--row">
  <div class="col-4"></div>
  <div class="col">
    <%= link_to "退会しない", my_page_users_path, class: "btn btn-block btn-outline-primary" %>
  </div>
  <div class="col-4"></div>
</div>

<div class="row user-myPage--row">
  <div class="col-4"></div>
  <div class="col">
    <%= link_to "退会する", out_users_path, method: :patch, class: "btn btn-block btn-outline-danger" %>
  </div>
  <div class="col-4"></div>
</div>