config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'about' => 'homes#about'

  resources :users, only: %i[edit update] do
    collection do
      get 'my_page'
      get 'quit'
      patch 'out'
    end
  end

  resources :events, only: %i[index new create show edit update destroy] do
    resources :maps, only: %i[create edit update destroy]
    resources :images, only: %i[create destroy]
  end
  get 'event/day' => 'events#day'
  get 'event/tag' => 'events#tag'

  resources :presets, only: %i[new create destroy]

  resources :groups, only: %i[index create show edit update] do
    get 'day'
  end

  resources :group_users, only: %i[create destroy]
  patch 'group_users/:id' => 'group_users#accept', as: :group_users_accept
  get 'group_users/:id' => 'group_users#reject', as: :group_users_reject
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.has_translation(*attributes)
    attributes.each do |attribute|
      define_method "#{attribute}" do
        self.send "#{attribute}_#{I18n.locale}"
      end
    end
  end

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :maps
  has_many :images, dependent: :destroy
  has_many  :tag_relationships, dependent: :destroy
  has_many  :tags, through: :tag_relationships
  accepts_attachments_for :images, attachment: :image, append: true

  # バリデーション
  validates :name, presence: true, length: { maximum: 20 }
  validates :place, length: { maximum: 20 }
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :end_time_check
  # 終了が開始より早くならないこと
  def end_time_check
    errors.add(:end_time, 'は開始時刻より遅い時間を選択してください') if start_time.present? && end_time.present? && (end_time < start_time)
  end

  # タグ機能
  def save_tags(save_event_tags)
    current_tags = tags.pluck(:name) unless tags.nil?  # タグがあればnameを抽出
    old_tags = current_tags - save_event_tags
    new_tags = save_event_tags - current_tags

    old_tags.each do |old_name|
      tags.delete Tag.find_by(name: old_name)
    end

    new_tags.each do |new_name|
      event_tag = Tag.find_or_create_by(name: new_name)
      tags << event_tag
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true, length: { maximum: 20 }
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :group_id, presence: true, uniqueness: { scope: [:user_id] }
  # validates :user_id, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :event

  attachment :image
end

app/models/map.rb
class Map < ApplicationRecord
  belongs_to :event

  validates :latitude, :longitude, :address, presence: true
  validates :name, presence: true, length: { maximum: 10 }

  geocoded_by :address
  before_validation :geocode
end

app/models/preset.rb
class Preset < ApplicationRecord

  belongs_to :user

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_relationships, dependent: :destroy
  has_many :events, through: :tag_relationships
  validates :name, presence: true, length: { maximum: 10 }
end

app/models/tag_relationship.rb
class TagRelationship < ApplicationRecord
  belongs_to :event
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :events, dependent: :destroy
  has_many :presets, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users

  validates :name, presence: true, length: { minimum: 2, maximum: 15 }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :tags

  def index
    @events = current_user.events.order(:start_time)
    @true_group_users = current_user.group_users.where(invitation: true) # 所属グループ
    @false_group_users = current_user.group_users.where(invitation: false) # 招待を受けているグループ
    @today_events = @events.where('end_time>=? and start_time<?', Date.today, Date.tomorrow).order(:start_time)
  end

  def day
    @day = Time.zone.parse(params[:day].to_s)
    user_events = Event.where(user_id: current_user.id)
    @events = user_events.where('end_time>=? and start_time<?', @day, @day.tomorrow)
    @before_events = @events.where('start_time<?', @day).order(:start_time) # 前日から続いてる予定
    @today_events = @events.where('start_time>=?', @day).order(:start_time) # 当日始まる予定
  end

  def new
    @event = Event.new
    @presets = current_user.presets
    gon.presets = @presets
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    tag_list = params[:event][:tag_ids].split(',') # 入力されたタグを,で区切って保存する
    if @event.save
      @event.save_tags(tag_list)
      flash[:success] = '予定が登録されました'
      redirect_to events_path
    else
      render 'new'
    end
  end

  def show
    # current.userが持つgroup_uerのgroup.idと@event.userの持つつgroup_uerのgroup.idに一致するものがあれば
    @event = Event.find_by_id(params[:id])
    if @event == nil  #存在しないIDなら一覧画面に飛ばす
      redirect_to '/events'
      return
    end
    c_group_ids = current_user.group_users.pluck(:group_id) # ログインユーザーの所属してるグループID
    e_group_ids = @event.user.group_users.pluck(:group_id) # イベントのユーザーの所属してるグループID
    group_match = c_group_ids & e_group_ids # 上２つの重複を探す
    # ログインユーザーと投稿ユーザーが一致 or (公開設定かつ同一のグループに所属している)
    if @event.user == current_user || (@event.release == true && group_match.empty? == false)
      @map = Map.new
      @maps = Map.where(event_id: @event.id)
      @map_pin = @maps.first
      @image = Image.new
    else
      redirect_to '/events'
    end
  end

  def edit
    @event = Event.find_by_id(params[:id])
    if @event == nil  #存在しないIDなら一覧画面に飛ばす
      redirect_to '/events'
      return
    end
    if @event.release == true  #公開設定のセレクトボックスの初期値用に1or0に変換
      @release = 1
    else
      @release = 0
    end
    @tag_list = @event.tags.pluck(:name).join(',')
    if @event.user == current_user # アクセス制限
      render 'edit'
    else
      redirect_to '/events'
    end
  end

  def update
    @event = Event.find(params[:id])
    # 画像の空投稿の場合、eventが渡ってこないので、そのままリダイレクト
    if params[:event].blank?
      flash[:danger] = '画像が登録できませんでした。'
      redirect_to event_path(@event)
      return
    end

    if @event.update(event_params)
      if params[:event][:tag_ids].present?
        tag_list = params[:event][:tag_ids].split(',')
        @event.save_tags(tag_list)
      end
      flash[:success] = '予定が更新されました'
      redirect_to event_path(@event)
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.user == current_user  # アクセス制限
      @event.destroy
      redirect_to events_path
    else
      redirect_to '/events'
    end
  end

  def tag
    @tag = Tag.find(params[:id])
    tag_relationships_event_ids = TagRelationship.where(tag_id: @tag.id).pluck(:event_id)
    @events = current_user.events.where(id: tag_relationships_event_ids)
  end

  private

  def event_params
    params.require(:event).permit(:user_id, :name, :detail, :remarks, :start_time, :end_time, :place, :release,
                                  images_images: [])
  end

  def tags
    @events = current_user.events.order(:start_time)
    event_ids = @events.pluck(:id)  # ユーザーの持つイベントのTagを抽出
    tag_relationships_tag_ids = TagRelationship.where(event_id: event_ids).pluck(:tag_id)
    @tags = Tag.where(id: tag_relationships_tag_ids) # ここまでTagの記述
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top; end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def create
    event = Event.find(params[:event_id])
    map = event.maps.new(map_params)
    map.event_id = event.id
    if map.save
      flash[:success] = 'ピンが登録されました'
    else
      flash[:danger] = 'ピンが登録できませんでした'
    end
    redirect_to event_path(event)
  end

  def destroy
    map = Map.find(params[:event_id])
    event = map.event
    map.destroy
    redirect_to event_path(event)
  end

  def map_params
    params.require(:map).permit(:name, :address, :latitude, :longitude)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/presets_helper.rb
module PresetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event_form.html.erb
<%= form_with(model: @event, class: "event-form", local: true) do |form| %>
<div class="row event-add--form d-flex justify-content-center">
  <div class="col-11 table-responsive-md">
    <table class="table table-bordered">
      <tbody>
        <tr scope="row">
          <th class="text-nowrap"><%= form.label :"予定のタイトル" %></th>
          <td>
            <%= form.text_field :name, autofocus: true, placeholder: "◯◯会議 , ◯◯に行く , 20文字以内で入力してください。", :size => "60*30" %><br>
            <%= render "layouts/error_messages", model: @event, attribute: :name %>
          </td>
        </tr>
        <tr scope="row">
          <th class="text-nowrap"><%= form.label :"場所" %></th>
          <td>
            <%= form.text_field :place, :size => "60*30", placeholder: "後から予定の場所をMAPでも登録できます" %><br>
            <%= render "layouts/error_messages", model: @event, attribute: :place %>
          </td>
        </tr>
        <tr scope="row">
          <th class="text-nowrap"><%= form.label :"時間" %></th>
          <td class="text-nowrap d-flex">
            <div>
              <%= form.datetime_field :start_time %><br>
              <%= render "layouts/error_messages", model: @event, attribute: :start_time %>
            </div>
            <div>　〜　</div>
            <div>
              <%= form.datetime_field :end_time %><br>
              <%= render "layouts/error_messages", model: @event, attribute: :end_time %>
            </div>
          </td>
        </tr>
        <tr scope="row">
          <th class="text-nowrap"><%= form.label :"予定の詳細" %></th>
          <td>
            <%= form.text_area :detail, size: "60x5" %>
            <%= render "layouts/error_messages", model: @event, attribute: :detail %>
          </td>
        </tr>
        <tr scope="row">
          <th class="text-nowrap"><%= form.label :"備考" %></th>
          <td>
            <%= form.text_area :remarks, size: "60x3", placeholder: "◯◯を持っていく！" %>
            <%= render "layouts/error_messages", model: @event, attribute: :remarks %>
          </td>
        </tr>
        <tr scope="row">
          <th class="text-nowrap"><%= form.label :"グループメンバーへの公開設定" %></th>
          <td class="event-form__release">
            <%= form.select :release, [['非公開',0],['公開',1]], selected: @release %>　<i class="far fa-question-circle event-form__release__q-icon" id="questionBtn"></i>

            <div class="event-form__release__q-box" id="eventNewQuestion">
              <div class="event-form__release__q-box__balloon"></div>
              <p class="event-form__release__q-box__text">
                「公開」にした場合、あなたが所属するグループメンバーがこの予定を閲覧できるようになります。<br>
                この設定は後から変更が出来ます。
              </p>
            </div>
          </td>
        </tr>
        <tr scope="row">
          <th class="text-nowrap">タグ</th>
          <td>
            <%= form_with model: @event, local: true do |form| %>
              <%= form.text_field :tag_ids, class: "form-control", value: @tag_list, placeholder: "複数つけるには「,」で区切ってください。" %>
            <% end %>
          </td>
        </tr>
        <tr scope="row">
          <th></th>
          <td><%= form.submit %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<% end %>

app/views/events/day.html.erb
<main class="event-day--main">
  <h3><%= @day.strftime('%m/%d') %>の予定</h3>
  <% if @events.present? %>
    <div class="table-responsive-md">
      <table class="table event-day--table">
        <% if @today_events.present? %>
          <thead class="thead-light">
            <tr scope="row">
              <th>
                <%= @day.strftime('%m/%d') %>から始まる予定
              </th>
              <th>予定</th>
              <th>場所</th>
            </tr>
          </thead>
          <tbody>
            <% @today_events.each do |event| %>
              <tr scope="row">
                <td class="text-nowrap"><%= event.start_time.strftime('%m/%d %H:%M') %>　〜　<%= event.end_time.strftime('%m/%d %H:%M') %></td>
                <td>
                  <%= link_to event_path(event), class: "event-day--table__event-link" do %>
                    <%= event.name %>
                  <% end %>
                </td>
                <td>
                  <% if event.place.present? %>
                    <%= event.place %>
                  <% else %>
                    -
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        <% end %>

        <% if @before_events.present? %>
          <thead class="thead-light">
            <th>
              前日から続いている予定
            </th>
            <th></th>
            <th></th>
          </thead>
          <tbody>
            <% @before_events.each do |event| %>
              <tr>
                <td><%= event.start_time.strftime('%m/%d %H:%M') %>　〜　<%= event.end_time.strftime('%m/%d %H:%M') %></td>
                <td>
                  <%= link_to event_path(event), class: "event-day--event_link" do %>
                    <%= event.name %>
                  <% end %>
                </td>
                <td>
                  <% if event.place.present? %>
                    場所：<%= event.place %>
                  <% else %>
                    場所：-
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        <% end %>
      </table>
    <% else %>
      <h5 class="text-center">登録された予定はありません</h5>
    <% end %>
  </div>
</main>

app/views/events/edit.html.erb
<main>
  <h2 class="text-center event-edit--title">予定の編集</h2>
  <%= render "event_form" %>
</main>

app/views/events/index.html.erb
<% if flash[:success].present? %>
  <p class="alert alert-success" role="alert"><%= flash[:success] %></p>
<% end %>

<main>
  <div class="row event-index--main_box">
    <!--メニュー部分-->
    <div class="col-xl-3 event-index--side">
      <nav class="navbar-expand-xl">
        <button class="navbar-toggler event-index--side__btn" type="button" data-toggle="collapse" data-target="#responsiveMenu" aria-controls="responsiveMenu" aria-expanded="false" aria-label="Toggle navigation">
          <span class="event-index--side__icon"><i class="fas fa-bars"></i></span>
        </button>
        <div class="collapse navbar-collapse" id="responsiveMenu">
          <ul class="event-index--side__ul">
            <!--予定の追加部分-->
            <li class="event-index--side__li">
              <%= link_to new_event_path, class: "event-index--new_link" do %>
                <span class="event-index--new_link__text">予定を追加　</span><i class="fas fa-plus-circle event-index--new_link__text"></i>
              <% end %>
            </li>
            <!--今日の予定部分-->
            <li class="event-index--side__li">
              <h5 class="event-index--today__title">本日の予定  <i class="fas fa-chevron-circle-right today-events-icon"></i>
            </li>
            <li class="event-index--side__li event-index--side__content event-index--today">
              <ul class="event-index--today__box">
                <% if @today_events.present? %>
                  <% @today_events.each do |event| %>
                    <%= link_to event_path(event), class: "event-index--today__box__link" do %>
                      <li class="event-index--today__box__link__li">
                        <p class="event-index--today__box__link__text text-left"><%= event.name %></p>
                      </li>
                    <% end %>
                  <% end %>
                <% else %>
                  <li>
                    <p class="event-index--none-data">登録されていません</p>
                  </li>
                <% end %>
              </ul>
            </li>

            <!--タグ一覧部分-->
            <li class="event-index--side__li">
              <h5 class="event-index--tag__title">タグ一覧  <i class="fas fa-chevron-circle-right tag-index-icon"></i></h5>
            </li>
            <li class="event-index--side__li event-index--side__content event-index--tag">
              <ul class="event-index--tag__menu">
                <% if @tags.present? %>
                  <% @tags.each do |tag| %>
                    <li class="event-index--tag__menu__li">
                      <%= link_to event_tag_path(id: tag.id), class: "event-index--tag__menu__li__link" do %>
                        <i class="fas fa-tag"></i>  <%= tag.name %>
                      <% end %>
                    </li>
                  <% end %>
                <% else %>
                <li>
                  <p class="event-index--none-data">登録されていません</p>
                </li>
                <% end %>
              </ul>
            </li>

            <!--所属グループ部分-->
            <li class="event-index--side__li">
              <h5 class="event-index--group__title">所属グループ  <i class="fas fa-chevron-circle-right group-index-icon"></i></h5>
            </li>
            <li class="event-index--side__li event-index--side__content event-index--group">
              <ul class="event-index--group__box">
                <% if @true_group_users.present? %>
                  <% @true_group_users.each do |group_user| %>
                    <%= link_to group_path(group_user.group), class: "event-index--group__box__link" do %>
                      <li class="event-index--group__box__link__li">
                        <p class="event-index--group__box__name"><%= group_user.group.name %></p>
                      </li>
                    <% end %>
                  <% end %>
                <% else %>
                  <p class="event-index--none-data">グループに所属していません</p>
                <% end %>
              </ul>
            </li>

            <!--承認待ちグループ部分-->
            <li class="event-index--side__li">
              <h5 class="event-index--invitation__title">招待中グループ  <i class="fas fa-chevron-circle-right invitation-index-icon"></i></h5>
            </li>
            <li class="event-index--side__li event-index--side__content event-index--invitation-content">
              <ul class="event-index--invitation">
                <div class="event-index--invitation__box">
                  <% if @false_group_users.present? %>
                    <% @false_group_users.each do |group_user| %>
                      <p class="event-index--invitation__box__name"><%= group_user.group.name %></p>
                      <div class="event-index--invitation__box__btn">
                        <%= form_with(model: group_user, url:group_users_accept_path(id: group_user.id) ,class: "event-index--invitation__box__btn__accept" ,local: true) do |f| %>
                          <%= f.hidden_field :invitation, :value => true %>
                          <%= f.submit "承認", class: "btn btn-sm btn-outline-success" %>
                        <% end %>
                        <%= link_to "拒否", group_users_reject_path(id: group_user.id), class: "btn btn-sm btn-outline-dark"  %>
                      </div>
                    <% end %>
                  <% else %>
                    <li>
                      <p>招待はありません</p>
                    </li>
                  <% end %>
                </div>
              </ul>
            </li>
          </ul>
        </div>
      </nav>
    </div>
  <!--カレンダー部分-->
    <div class="col-xl-8 col-lg-11 event-index--calendar">
      <div class="event-index--calendar__inside">
        <%= month_calendar events: @events do |date, events| %>
          <%= date.day %>
          <!--日付の中に表示する予定-->
          <% events.first(3).each do |event| %>
            <div class="event-index--calendar__inside__name-box">
              <%= link_to event_path(event), class: "event-index--calendar__inside__name-box__link" do %>
                <p class="event-index--calendar__inside__name-box__name"><%= event.name %></p>
              <% end %>
            </div>
          <% end %>
          <!--４つ以上なら3点で省略-->
          <% if events.count >= 4 %>
            <div class="text-left event-index--day_dot">
              <i class="fas fa-ellipsis-v fa-xs"></i>
            </div>
          <% end %>
          <!--その日の予定数-->
          <% if events.present? %>
            <div class="event-index--calendar__inside__day-count">
              <%= link_to event_day_path(day: date), class: "event-index--calendar__inside__day-count__link" do %>
                予定：<%= events.count %>件
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/events/new.html.erb
<main>
  <h2 class="text-center event-new--title">予定の追加</h2>

  <h6 class="event-new--preset_title">プリセット一覧  <i class="fas fa-chevron-circle-right preset-index-icon"></i></h6>
  <div class="preset">
    <div class="preset__index d-flex flex-wrap flex-lg-nowrap">
      <% if @presets.present? %>
        <% @presets.each_with_index do |preset, i| %>
          <div class="preset__index__box d-flex align-items-center">
            <div class="preset__index__box__name" id="preset_<%= i %>">
              <%= preset.name %>
            </div>
            <div class="preset__index__box__delete">
              <%= link_to "", preset_path(preset), method: :delete, class: "btn-danger fas fa-backspace preset__index__box__delete__btn" %>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>
          プリセットが</br>
          登録されていません。
          </p>
      <% end %>

    </div>
    <div class="preset__link-box">
      <%= link_to "  プリセットの登録", new_preset_path, class: "fas fa-plus-circle preset__link-box__link" %>
    </div>
  </div>

  <%= render "event_form" %>
</main>

app/views/events/show.html.erb
<% if flash[:success].present? %>
  <p class="alert alert-success" role="alert"><%= flash[:success] %></p>
<% end %>
<% if flash[:danger].present? %>
  <p class="alert alert-danger" role="alert"><%= flash[:danger] %></p>
<% end %>

<main class="row event-show--main_box d-flex justify-content-around">
  <!--予定の登録内容-->
  <div class="col-lg-6">
    <div class="event-show--event-box">
      <div>
        <h3><%= @event.start_time.strftime('%m/%d %H:%M:%S') %> ~ <%= @event.end_time.strftime('%m/%d %H:%M:%S') %></h3>
      </div>
      <div class="event-show--event-box__name">
        <h3>予定</h3>
        <p class="event-show-event-box__name__text"><%= @event.name %></p>
      </div>
      <div class="event-show--event-box__place">
        <h3>場所</h3>
        <p class="event-show--event-box__place_text"><%= @event.place %></p>
      </div>
      <div class="event-show--event-box__detail">
        <h3>詳細</h3>
        <p class="event-show--event-box__detail__text"><%= simple_format(@event.detail) %></p>
      </div>
      <div class="event-show--event-box__remarks">
        <h3>備考</h3>
        <p class="event-show--event-box__remarks__text"><%= simple_format(@event.remarks) %></p>
      </div>
      <div class="event-show--event-box__event-btn text-right">
        <% if @event.user == current_user %>
          <%= link_to '予定の変更', edit_event_path(@event.id), class: 'btn btn-outline-dark' %>
          <%= link_to '予定の削除', event_path(@event.id), method: :delete, class: 'btn btn-outline-dark' %>
        <% end %>
      </div>
    </div>
  </div>
  <!--MapとImage関連-->
  <div class="col-lg-5">
    <div class="event-show--map">
      <h4>Map</h4>
      <div class="event-show--map__map-box">
        <% if @event.user == current_user %>
          <input id="address" type="textbox" value="">
          <input type="button" value="検索" name="検索" onclick="codeAddress()">
        <% end %>
        <div class="event-show--map__map-box__map" id="map"></div>  <!--map本体-->
        <% if @event.user == current_user %>
          <%= form_with(model:[@event, @map], html:{class: "event-show--map__map-box__form"},local: true) do |f| %>
            <input type="hidden" name="map[address]" id="hidden_address">
            <%= f.label :name, "ピンの登録" %>
            <%= f.text_field :name %>
            <%= f.submit "保存" %>
          <% end %>
        <% end %>
      </div>
      <div class="event-show--map__pin">
        <h5 class="event-show--map__pin__title">登録したピン：</h5>
        <% if @maps.present? %>
          <% @maps.each do |map| %>
            <div class="event-show--map__pin__box">
              <i class="fas fa-map-marker-alt"></i>
              <%= map.name %>
              <%= link_to "", event_map_path(map), method: :delete, class: "btn-danger fa-xs fas fa-backspace event-show--map__pin__box__delete" %>
            </div>
          <% end %>
        <% else %>
          ピンが登録されていません
        <% end %>
      </div>
    </div>

    <div class="event-show--image">
      <h4 class="event-show--image__title">登録画像</h4>
      <div>
        <% if @event.images.present? %>
          <% @event.images.each do |image| %>
            <div class="event-show--image__box">
              <%= attachment_image_tag image, :image, :fill, 160, 160, size:'160x160' %>
              <%= link_to "", event_image_path(image), method: :delete, class: "btn-danger fas fa-backspace event-show--image__box__delete" %>
            </div>
          <% end %>
        <% else %>
          画像はありません。
        <% end %>
      </div>

      <div class="event-show--image__form">
        <% if @event.user == current_user %>
          <%= form_with(model: @event, local: true) do |f| %>
            <%= f.attachment_field :images_images, multiple: true, placeholder: "追加画像", class: "" %>
            <%= f.submit "画像を登録", class: "event-show--image__form__btn" %>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
</main>

<!--以下googleMap情報-->
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap" async defer></script>

<script>
  let map
  let geocoder
  let marker

  function initMap() {
    geocoder = new google.maps.Geocoder()
    mapInstance = new google.maps.Map(document.getElementById('map'), {
      center: {
        <% if @maps.present? %>
          lat: <%= @map_pin.latitude %>,
          lng: <%= @map_pin.longitude %>
        <% else %>
          lat: 35.681,
          lng: 139.767
        <% end %>
      },
      zoom: 13
    });

    // 保存された地図情報からピンをさす
    <% @maps.each do |map| %>
    pos = new google.maps.LatLng(
    <%= map.latitude %>,
    <%= map.longitude %>
    );
    default_marker = new google.maps.Marker({
    map: mapInstance,
    position: pos,
    icon: {
    url: ' https://maps.google.com/mapfiles/ms/icons/green-dot.png',
    scaledSize: new google.maps.Size(40, 40)
    }
    });
    <% end %>
  }

  function codeAddress() {
    let inputAddress = document.getElementById('address').value;
    geocoder.geocode({
      'address': inputAddress
    }, function (results, status) {
      if (status == 'OK') {
        mapInstance.setCenter(results[0].geometry.location);
        if(marker != null){
        marker.setMap(null);
        }
        marker = null;
        marker = new google.maps.Marker({
          map: mapInstance,
          position: results[0].geometry.location
        });

        let title = document.getElementById('map_name');
        title.setAttribute("value", inputAddress);

        let hidden_address = document.getElementById('hidden_address');
        hidden_address.setAttribute("value", inputAddress);
      } else {
        alert('有効な文字を入力してください。');
      }
    });
  }
</script>

app/views/events/tag.html.erb
<div class="row event-tag--main">
  <div class="col-lg-2"></div>
  <div class="col-lg-8 col-md-11 event-tag--calendar">
    <h4 class="text-left"><i class="fas fa-tag"></i>  <%= @tag.name %></h4>
    <div class="event-tag--calendar__inside">
      <%= month_calendar events: @events do |date, events| %>
        <%= date.day %>
        <!--日付の中に表示する予定-->
        <% events.first(3).each do |event| %>
          <div class="event-tag--calendar__inside__name-box">
            <%= link_to event_path(event), class: "event-tag--calendar__inside__name-box__link" do %>
              <p class="event-tag--calendar__inside__name-box__name"><%= event.name %></p>
            <% end %>
          </div>
        <% end %>
        <!--４つ以上なら3点で省略-->
        <% if events.count >= 4 %>
          <div class="text-left event-tag--day_dot">
            <i class="fas fa-ellipsis-v fa-xs"></i>
          </div>
        <% end %>
        <!--その日の予定数-->
        <% if events.present? %>
          <div class="event-tag--calendar__inside__day-count">
            <%= link_to event_day_path(day: date), class: "event-tag--calendar__inside__day-count__link" do %>
              予定：<%= events.count %>件
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>