config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'about' => 'homes#about'

  resources :users, only: %i[edit update] do
    collection do
      get 'my_page'
      get 'quit'
      patch 'out'
    end
  end

  resources :events, only: %i[index new create show edit update destroy] do
    resources :maps, only: %i[create edit update destroy]
    resources :images, only: %i[create destroy]
  end
  get 'event/day' => 'events#day'
  get 'event/tag' => 'events#tag'

  resources :presets, only: %i[new create destroy]

  resources :groups, only: %i[index create show edit update] do
    get 'day'
  end

  resources :group_users, only: %i[create destroy]
  patch 'group_users/:id' => 'group_users#accept', as: :group_users_accept
  get 'group_users/:id' => 'group_users#reject', as: :group_users_reject
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.has_translation(*attributes)
    attributes.each do |attribute|
      define_method "#{attribute}" do
        self.send "#{attribute}_#{I18n.locale}"
      end
    end
  end

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :maps
  has_many :images, dependent: :destroy
  has_many  :tag_relationships, dependent: :destroy
  has_many  :tags, through: :tag_relationships
  accepts_attachments_for :images, attachment: :image, append: true

  # バリデーション
  validates :name, presence: true, length: { maximum: 20 }
  validates :place, length: { maximum: 20 }
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :end_time_check
  # 終了が開始より早くならないこと
  def end_time_check
    errors.add(:end_time, 'は開始時刻より遅い時間を選択してください') if start_time.present? && end_time.present? && (end_time < start_time)
  end

  # タグ機能
  def save_tags(save_event_tags)
    current_tags = tags.pluck(:name) unless tags.nil?  # タグがあればnameを抽出
    old_tags = current_tags - save_event_tags
    new_tags = save_event_tags - current_tags

    old_tags.each do |old_name|
      tags.delete Tag.find_by(name: old_name)
    end

    new_tags.each do |new_name|
      event_tag = Tag.find_or_create_by(name: new_name)
      tags << event_tag
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true, length: { maximum: 20 }
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :group_id, presence: true, uniqueness: { scope: [:user_id] }
  # validates :user_id, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :event

  attachment :image
end

app/models/map.rb
class Map < ApplicationRecord
  belongs_to :event

  validates :latitude, :longitude, :address, presence: true
  validates :name, presence: true, length: { maximum: 10 }

  geocoded_by :address
  before_validation :geocode
end

app/models/preset.rb
class Preset < ApplicationRecord

  belongs_to :user

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_relationships, dependent: :destroy
  has_many :events, through: :tag_relationships
  validates :name, presence: true, length: { maximum: 10 }
end

app/models/tag_relationship.rb
class TagRelationship < ApplicationRecord
  belongs_to :event
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :events, dependent: :destroy
  has_many :presets, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users

  validates :name, presence: true, length: { minimum: 2, maximum: 15 }
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/presets_helper.rb
module PresetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <% model.errors.full_messages_for(attribute).each do |message| %>
    <div class="alert-warning error_message_text"><%= message %></div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="py-1 text-center bg-dark footer">
  <p class="text-light footer-text">fumi-detail.com</p>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "detail", root_path, class: "header-logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"><%= link_to " 今月の予定", events_path, class: "btn fas fa-calendar-alt text-white" %></li>
          <li class="nav-item"><%= link_to " グループ", groups_path, class: "btn fas fa-users text-white" %></li>
          <li class="nav-item"><%= link_to " マイページ", my_page_users_path, class: "btn fas fa-child text-white" %></li>
          <li class="nav-item"><%= link_to " ログアウト", destroy_user_session_path, method: :delete, class: "btn fas fa-sign-out-alt text-white" %></li>
          <li class="nav-item text-white"><div class="header-user_info">ログイン中：<%= current_user.name %></div></li>
          <li class="nav-item text-white"><div class="header-user_info">ユーザーID：<%= current_user.id %></div></li>
        </ul>
      </div>

    <% else %>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <!--<li class="nav-item"><%= link_to " About",    about_path, class: "btn fas fa-question text-white" %></li>-->
          <li class="nav-item"><%= link_to " 新規登録", new_user_registration_path, class: "btn fas fa-user text-white" %></li>
          <li class="nav-item"><%= link_to " ログイン", new_user_session_path, class: "btn fas fa-sign-in-alt text-white" %></li>
        </ul>
      </div>
    <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Detail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= include_gon %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!--フォント用link-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.ico') %>
  </head>

  <body>
    <div class="content">
      <%= render 'layouts/header' %>
      <%= yield %>
      <div class="push"></div>
    </div>
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <div class="text-center calendar-month--title">
      <%= link_to t('simple_calendar.previous', default: ''), calendar.url_for_previous_view, class: "fas fa-angle-double-left" %>
      <span class="calendar-title"><%= start_date.year %> / <%= t('date.month_names')[start_date.month] %></span>
      <%= link_to t('simple_calendar.next', default: ''), calendar.url_for_next_view, class: "fas fa-angle-double-right" %>
    </div>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr class="calender-month--day">
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <div class="text-center calendar-week--title">
      <%= link_to t('simple_calendar.previous', default: ''), calendar.url_for_previous_view, class: "fas fa-angle-double-left" %>
      <% if calendar.number_of_weeks == 1 %>
        <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
      <% else %>
        <span class="calendar-title"><%= t('simple_calendar.week', default: '') %> <%= start_date.year %> / <%= start_date.month %></span>
      <% end %>
      <%= link_to t('simple_calendar.next', default: ''), calendar.url_for_next_view, class: "fas fa-angle-double-right" %>
    </div>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr class="calender-week--day">
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>